# Generated by Django 4.0.2 on 2022-02-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='taxt_price',
            new_name='tax_price',
        ),
    ]
